### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by GGhuyongheng** [NVSL/NOVA#11]
I come across a problem that after building up the kernel 4.3.6 in Centos 6.5, I add "memmap=4G!8G" when the kernel boots, and use "dmesg" to check ,I can see the reserved 4G persistent memory but there is no pmem0 under the dir /dev. Anyone knows why ?

**Comment by Andiry** [comment]
Please make sure you have enabled Persistent memory block device support in the kernel:

CONFIG_BLK_DEV_PMEM = m

It is under the NVDIMM support, in device drivers.

**Comment by GGhuyongheng** [comment]
Thank you! I have solved this problem. By the way,could you tell me how can I get the Persistent Memory Emulation Platform (PMEP) . Since the author didn't leave the email address, I can't get touch with the author.Thank you again!

**Comment by Andiry** [comment]
PMEP is managed by Intel. You need to contact Intel to gain access to the PMEP.

**Comment by GGhuyongheng** [comment]
OK，thank you！So, your PMEP is supported by Intel or bought from Intel? And I'd be very grateful if you could tell me the contact information about the person or department of Intel that manage the PMEP! By the way, I'm very interested in NOVA and plan to do some research on it , hoping to get some help from you. Thank you very much!

**Comment by Andiry** [comment]
That is beyond my control. You can always run NOVA on any regular platform with enough memory.
